packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/compat': ^1.4.0
  '@eslint/js': ^9.37.0
  '@tanstack/form-core': ^1.24.1
  '@tanstack/solid-form': ^1.23.5
  '@tanstack/solid-router': ^1.132.41
  '@tanstack/solid-table': ^8.21.3
  '@typescript-eslint/eslint-plugin': ^8.46.0
  '@typescript-eslint/parser': ^8.46.0
  chart.js: ^4.5.0
  clsx: ^2.1.1
  convex: ^1.27.3
  eslint: ^9.37.0
  eslint-plugin-solid: ^0.14.5
  solid-motionone: ^1.0.4
  solid-sonner: ^0.2.8
  solid-ui: ^2.6.1
  typescript-eslint: ^8.46.0
